# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: konser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'konser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckonser.proto\x12\x06konser\"*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"M\n\x06Konser\x12\x0c\n\x04nama\x18\x01 \x01(\t\x12\x0e\n\x06lokasi\x18\x02 \x01(\t\x12\x0f\n\x07tanggal\x18\x03 \x01(\t\x12\x14\n\x0cjumlah_tiket\x18\x04 \x01(\x05\"\x17\n\x06Status\x12\r\n\x05pesan\x18\x01 \x01(\t\"1\n\x10RegisterResponse\x12\x0e\n\x06sukses\x18\x01 \x01(\x08\x12\r\n\x05pesan\x18\x02 \x01(\t\".\n\rLoginResponse\x12\x0e\n\x06sukses\x18\x01 \x01(\x08\x12\r\n\x05pesan\x18\x02 \x01(\t\"3\n\x0cTiketRequest\x12\x13\n\x0bkonser_nama\x18\x01 \x01(\t\x12\x0e\n\x06jumlah\x18\x02 \x01(\x05\"-\n\rTiketResponse\x12\r\n\x05pesan\x18\x01 \x01(\t\x12\r\n\x05total\x18\x02 \x01(\x05\"*\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05pesan\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x18\n\x08KonserId\x12\x0c\n\x04nama\x18\x01 \x01(\t\"0\n\x0fGeneralResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05pesan\x18\x02 \x01(\t2\xf2\x03\n\rKonserService\x12\x36\n\x0cRegisterUser\x12\x0c.konser.User\x1a\x18.konser.RegisterResponse\x12\x30\n\tLoginUser\x12\x0c.konser.User\x1a\x15.konser.LoginResponse\x12.\n\x0cTambahKonser\x12\x0e.konser.Konser\x1a\x0e.konser.Status\x12,\n\nEditKonser\x12\x0e.konser.Konser\x1a\x0e.konser.Status\x12/\n\x0bHapusKonser\x12\x10.konser.KonserId\x1a\x0e.konser.Status\x12\x39\n\nPesanTiket\x12\x14.konser.TiketRequest\x1a\x15.konser.TiketResponse\x12\x33\n\x10LihatSemuaKonser\x12\r.konser.Empty\x1a\x0e.konser.Konser0\x01\x12>\n\x0bPesanBanyak\x12\x14.konser.TiketRequest\x1a\x17.konser.GeneralResponse(\x01\x12\x38\n\x08LiveChat\x12\x13.konser.ChatMessage\x1a\x13.konser.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'konser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=24
  _globals['_USER']._serialized_end=66
  _globals['_KONSER']._serialized_start=68
  _globals['_KONSER']._serialized_end=145
  _globals['_STATUS']._serialized_start=147
  _globals['_STATUS']._serialized_end=170
  _globals['_REGISTERRESPONSE']._serialized_start=172
  _globals['_REGISTERRESPONSE']._serialized_end=221
  _globals['_LOGINRESPONSE']._serialized_start=223
  _globals['_LOGINRESPONSE']._serialized_end=269
  _globals['_TIKETREQUEST']._serialized_start=271
  _globals['_TIKETREQUEST']._serialized_end=322
  _globals['_TIKETRESPONSE']._serialized_start=324
  _globals['_TIKETRESPONSE']._serialized_end=369
  _globals['_CHATMESSAGE']._serialized_start=371
  _globals['_CHATMESSAGE']._serialized_end=413
  _globals['_EMPTY']._serialized_start=415
  _globals['_EMPTY']._serialized_end=422
  _globals['_KONSERID']._serialized_start=424
  _globals['_KONSERID']._serialized_end=448
  _globals['_GENERALRESPONSE']._serialized_start=450
  _globals['_GENERALRESPONSE']._serialized_end=498
  _globals['_KONSERSERVICE']._serialized_start=501
  _globals['_KONSERSERVICE']._serialized_end=999
# @@protoc_insertion_point(module_scope)
